services:
  - type: web
    name: smart-event-hub-backend
    env: java
    rootDir: backend
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: prod
